---
title: Whether the Hiatus Actually Exists
draft: true
---

I previously believed that the "global warming hiatus"
referred to the period from 1998 to 2012.
However, around 2016, many studies questioned this definition,
with some even arguing that no such hiatus actually occurred.

## The argue

The main documents related to this dispute are listed below:

- @medhaug2017, Nature(Research Analysis):
  The so-called "hiatus" is a phenomenon resulting from the combined effects
  of definitions, observational coverage, internal natural variations,
  and external forcing.
  It does not mean that long-term human-induced warming has stopped.
- @lewandowsky2015, Scientific Reports:
  There are no recognizable hiatuses or pauses in the data.
  What’s observed is simply
  the normal variability associated with modern warming.
  When examined from various perspectives,
  the trend over the past 17 years remains significant across all time periods.
  Short-term trends, however, are often not significant due to
  insufficient statistical power resulting from small sample sizes.
  These short-term fluctuations don’t represent actual pauses in warming.
- @fyfe2016, Nature Climate Change:
  There has been a temporary slowdown, not a statistical illusion.
  This phenomenon was indeed observed between 2001 and 2014.
  However, it doesn’t represent a change in the long-term trend.
  It’s merely a short-term fluctuation
  within the overall long-term warming trend.

