---
title: 'fyfe2016: Making Sense of the Early-2000s Warming Slowdown'
created: 2026-04-22
last_modified: 2026-07-06 23:18:31
---

NCC commentary, slowdown was real, but not a stop, and mainly driven by internal decadal
variability plus natural forcing.

---

- citation_key: fyfe2016
- title: Making Sense of the Early-2000s Warming Slowdown
- author: John C. Fyfe, Gerald A. Meehl, Matthew H. England, Michael E. Mann, Benjamin D. Santer, Gregory M. Flato, Ed Hawkins, Nathan P. Gillett, Shang-Ping Xie, Yu Kosaka, Neil C. Swart
- journal: Nature Climate Change
- year: 2016
- doi: 10.1038/nclimate2938

## If there is a "hiatus"?

Some paper argues that the "hiatus" or "slowdown" is not real, lack of
statistical significance, or just a bais in the data.

This paper says it's real, statistically observable.

One important point is that we should pick the baseline period carefully.
Some papers pick 1950-1999 and argue that the slowdown is not there.
But the period that has the similar physical processes and human influence with
the under review period (about 2001-2014) should be 1972-2001.

## .

The vital scientific question is not "is there a hiatus/slowdown",
but "how do the internal variability and external forcing combine
and influence the surface temperature trend".
